#!/bin/bash
#*************************************************************************************
# delLock use by xrdp
# Use without argument. Launch by startwm.sh to delete lock file in dbeaver.
#*************************************************************************************
# D. Malki : Creation     10/05/2020  VERSION: 1.00
#*************************************************************************************
# load functions
cd /logiciel/scripts
local_path=$(dirname $(readlink -f $0))
. $local_path/functions
delFileIfExist $local_user_share_path/$dbeaver_profile_folder/workspace6/.metadata/.lock
exit 0
