#!/bin/bash
#*************************************************************************************
# file used for bucket connection
# Use with no argument
# get from vault credentials and generate the credential file for bucket access
#*************************************************************************************
# D. Malki : Creation     10/05/2020  VERSION: 1.00
#*************************************************************************************
#. /etc/rc.d/init.d/functions
#local_path=$(dirname $(readlink -f $0))
local_path=/logiciel/scripts
. $local_path/functions
dba=$(isDBAFromUser $USER)
env=$(getEnvFromUser $USER)
if [[ "$clouder" == "aws" ]]; then
  delFileIfExist ~/.passwd-s3fs
  accessKey=$(getVaultFieldFromUser $USER accessKey)
  secretKey=$(getVaultFieldFromUser $USER secretKey)
  echo $accessKey:$secretKey > ~/.passwd-s3fs
  chmod 600 ~/.passwd-s3fs
fi
if [[ "$clouder" == "gcp" ]]; then
  rm -rf ~/.credentials
  mkdir ~/.credentials
  saKey=$(getVaultFieldFromUser $USER saKey)
  if [[ ${#saKey} -ge 5 ]]; then
    echo $saKey > ~/.credentials/credential.json
    chmod 600 ~/.credentials/credential.json
  fi
fi
