#!/bin/bash
#*************************************************************************************
# start tool needed for the database connection
# Use without argument
#*************************************************************************************
# D. Malki : Creation     10/05/2020  VERSION: 1.00
#*************************************************************************************
#. /etc/rc.d/init.d/functions
#local_path=$(dirname $(readlink -f $0))
rm -rf ~/*.log
local_path=/logiciel/scripts
. $local_path/functions
sia=$(getSIAFromUser $USER)
if [[ "$clouder" == "gcp" ]]; then
  isYetMount=$(mount | grep "$USER on /home/$USER/$mountPoint type fuse")
fi
if [[ "$isYetMount" != *" on /home/$USER/$mountPoint"* ]]; then
  # at first create folder if it doen't yet exist
  rm -rf ~/$mountPoint
  mkdir ~/$mountPoint
  #generate credentials
  . $local_path/generateBucketCredential
  envIndexed=$(getEnvFromUser $USER)
  userEnv=${envIndexed:0:3}
  if [[ "$clouder" == "gcp" ]]; then
    if [[ -f /home/$USER/.credentials/credential.json ]]; then
      echo $bucketTool -key-file=/home/$USER/.credentials/credential.json $USER /home/$USER/$mountPoint
    fi
  fi
fi
